\bdutch

# Nederlandstalige samenvatting {.unnumbered}

De Europese paling (*Anguilla anguilla L.*) wordt al decennialang geconfronteerd met een sterke populatiedaling in Europa en behoort inmiddels tot de meest bedreigde vissoorten in Europa. Een van de belangrijkste knelpunten voor de populatie is de beperkte stroomopwaartse migratie van glasaal. In Vlaanderen vormen de Ijzermonding in Nieuwpoort, het sluizencomplex "Sas Slijkens" aan de monding van het Kanaal Gent-Oostende (KGO), en het uitwateringscomplex in Zeebrugge (monding van het Afleidingskanaal van de Leie, AKL, en het Leopoldkanaal, LK) cruciale intrekroutes voor glasaal. In eerder onderzoek werd glasaalmigratie geanalyseerd en werden mogelijke mitigerende maatregelen bij spuiconstructies in de Ganzepoot (Ijzermonding), Sas Slijkens (KGO), en het uitwateringscomplex Zeebrugge geëvalueerd. Het op een kier zetten van sluisdeuren tijdens het opkomend tij bleek een effectieve en kostenefficiënte methode om stroomopwaartse migratie te verbeteren, zonder het risico op verzilting van de polders door zeewaterinstroom. In 2015 werd er geen aangepast spuibeheer toegepast op deze locaties. Toch werden verhoogde conductiviteitswaarden gemeten, zoals gerapporteerd in het interne rapport *“Opvolging van de zoutintrusie in de Ijzer, het Kanaal Gent-Oostende, het Leopoldkanaal en het Afleidingskanaal van de Leie: Nulmeting 2015”* van het Instituut voor Natuur- en Bosonderzoek (INBO). Deze nulmetingen toonden regelmatig verhoogde geleidbaarheid, vooral nabij uitwateringsconstructies en verder stroomopwaarts. De hogere waarden werden toegeschreven aan locatie-specifiek beheer of natuurlijke verzilting, met name tijdens droge periodes met lage afvoer. Vanaf 2016 werd aangepast spuibeheer toegepast. De resultaten hiervan zijn gerapporteerd in opeenvolgende interne rapporten. In 2025 werd gepland om het aangepast spuibeheer voor te zetten van 1 maart tot 15 mei, maar door het droog voorjaar werd het op de meeste sites vroegtijdig stilgelegd en niet meer opnieuw opgestart. De toepassing van aangepast spuibeheer varieert sterk per waterloop. Dit hangt samen met verschillen in streefpeilen (m TAW), wat invloed heeft op het beschikbare tijdsvenster voor spuibeheer. Bovendien zijn sommige uitwateringsconstructies, zoals de Ganzepoot aan de Ijzer, permanent bemand, waardoor het beheer ook buiten kantooruren kan plaatsvinden, in tegenstelling tot het AKL en LK.

Het aangepast spuibeheer speelde een wisselende, maar cruciale rol in de glasaalmigratie langs de Vlaamse kust tussen 2022 en 2024, wat resulteerde in een sterke stijging van het aantal opzwemmende glasalen tot een piek van 671.014 in 2024. De IJzer kende de meest intensieve inzet en de meest uitgesproken zoutintrusie, waarbij pieken in geleidbaarheid sterk overeenkwamen met de AS-momenten, hoewel deze intensieve aanpak de migratie van een aanzienlijk aantal glasalen ondersteunde. In het Kanaal Gent-Oostende (KGO) en het Leopoldkanaal (LK) resulteerde het aangepast spuibeheer wel in een verhoogd zoutgehalte nabij de spuischuiven, maar in de jaren 2023 en 2024 bleven inlandse verhogingen grotendeels uit. Het Afleidingskanaal van de Leie (AKL) kende de minst intensieve inzet, zonder wezenlijke invloed op de geleidbaarheid landinwaarts, terwijl in de Noordede korte maar talrijke aangepast-spuibeheer-events een effectieve methode bleken om zoutintrusie lokaal te beperken. Over het algemeen konden de zoutlenzen in de periode tot en met 2024 snel en gemakkelijk naar zee worden gespuid. De vroegtijdige stopzetting van het beheer en resulterende ingeschatte daling tot 315.794 glasalen in 2025, was noodzakelijk omdat de zoutintrusie door het droge voorjaar al vroeg kritiek werd. Dit benadrukt de kwetsbaarheid van het beheer tijdens droogteperiodes en beklemtoont het belang van een goede opvolging en snelle handeling.

Naast een verderzetting van de monitoring wordt aangeraden om een meer gedetailleerde analyse te maken die toelaat om de momenten, frequentie en duur van het aangepast spuibeheer te optimaliseren in functie van zowel de bestrijding van zoutintrusie en het bevorderen van stroomopwaartse vismigratie.

\edutch
