\bdutch

# Nederlandstalige samenvatting {.unnumbered}

De Europese paling (*Anguilla anguilla L.*) wordt al decennialang geconfronteerd met een sterke populatiedaling in Europa en behoort inmiddels tot de meest bedreigde vissoorten in Europa. Een van de belangrijkste knelpunten voor de populatie is de beperkte stroomopwaartse migratie van glasaal. In Vlaanderen vormen de Ijzermonding in Nieuwpoort, het sluizencomplex "Sas Slijkens" aan de monding van het Kanaal Gent-Oostende (KGO), en het uitwateringscomplex in Zeebrugge (monding van het Afleidingskanaal van de Leie, AKL, en het Leopoldkanaal, LK) cruciale intrekroutes voor glasaal. Eerder onderzoek analyseerde glasaalmigratie en evalueerde mogelijke mitigerende maatregelen bij spuiconstructies in de Ganzepoot (Ijzermonding), Sas Slijkens (KGO), en het uitwateringscomplex Zeebrugge. Het op een kier zetten van sluisdeuren tijdens het opkomend tij bleek een effectieve en kostenefficiënte methode om stroomopwaartse migratie te verbeteren, zonder het risico op verzilting van de polders door zeewaterinstroom. In 2015 werd er geen alternatief spuibeheer toegepast op deze locaties. Toch werden verhoogde conductiviteitswaarden gemeten, zoals gerapporteerd in het interne rapport *“Opvolging van de zoutintrusie in de Ijzer, het Kanaal Gent-Oostende, het Leopoldkanaal en het Afleidingskanaal van de Leie: Nulmeting 2015”* van het Instituut voor Natuur- en Bosonderzoek (INBO). Deze nulmetingen toonden regelmatig verhoogde geleidbaarheid, vooral nabij uitwateringsconstructies en verder stroomopwaarts. De hogere waarden werden toegeschreven aan locatie-specifiek beheer of natuurlijke verzilting, met name tijdens droge periodes met lage afvoer. Vanaf 2016 werd alternatief spuibeheer toegepast. De resultaten hiervan zijn gerapporteerd in opeenvolgende interne rapporten. In 2023 werd alternatief spuibeheer voortgezet van 1 maart tot 15 mei. De toepassing van alternatief spuibeheer varieert sterk per waterloop. Dit hangt samen met verschillen in streefpeilen (m TAW), wat invloed heeft op het beschikbare tijdsvenster voor spuibeheer. Bovendien zijn sommige uitwateringsconstructies, zoals de Ganzepoot aan de Ijzer, permanent bemand, waardoor het beheer ook buiten kantooruren kan plaatsvinden, in tegenstelling tot het AKL en LK.

Zoutintrusie als gevolg van aangepast spuibeheer lijkt zich vooral voor te doen in het Ijzerbekken, waar pieken in geleidbaarheid sterk samenvallen met momenten van aangepast spuibeheer. Dit is grotendeels te verklaren door de intensieve toepassing van deze maatregel in de Ijzer, die resulteert in de succesvolle migratie van naar schatting 250.000 glasalen. Ter vergelijking: de inschattingen voor andere waterlopen tonen aanzienlijk lagere aantallen migrerende glasalen. In het Afleidingskanaal van de Leie (AKL) heeft het sporadisch toegepaste spuibeheer in 2023 geen waarneembaar effect op de geleidbaarheid. Het ingeschatte aantal glasalen dat hier kon migreren, bedraagt slechts 3% van het aantal dat de Ijzer opzwemt. In het Kanaal Gent-Oostende (KGO) en het Leopoldkanaal (LK) ligt dit percentage respectievelijk op 19% en 12%. Voor het KGO en LK is er sprake van een intensievere toepassing van aangepast spuibeheer dan in het AKL, wat wel leidt tot verhoogde geleidbaarheid nabij de spuischuiven van het KGO en LK op momenten van aangepast spuibeheer. Anders dan bij de Ijzer blijven deze effecten echter beperkt tot de directe omgeving en worden geen verhogingen dieper het binnenland in waargenomen. In de Noordede heeft het aangepaste spuibeheer in 2023 geen significante invloed gehad op de geleidbaarheid, ondanks een totale duur die ongeveer twee keer zo lang was als in het Kanaal Gent-Oostende en het Leopoldkanaal. Dit verschil kan mogelijk worden toegeschreven aan de specifieke frequentie en duur van de spuimomenten. In de Noordede werden de spuien gedurende ongeveer de helft van de totale tijdsduur van de Ijzer geopend, maar het aantal spuimomenten was twee keer zo hoog, met kortere spuimomenten per keer. Deze strategie van kortere, frequentere en goed getimede spuimomenten lijkt voordelen te bieden. Glasalen verzamelen zich doorgaans bij barrières voordat ze kunnen migreren. Door meerdere kortere momenten van spuibeheer te creëren, wordt de migratie van glasalen gefaciliteerd en kan zoutintrusie worden beperkt. Dit benadrukt het belang van een locatie-specifieke aanpak en een zorgvuldig afgestemde timing van spuibeheer om zowel de ecologische als de hydrologische doelen te bereiken.

\edutch
