\benglish

# English abstract {.unnumbered}

The European eel (Anguilla anguilla L.) has been facing a sharp population decline in Europe for decades and is now among the most endangered fish species in Europe. One of the main population bottlenecks is the limited upstream migration of glass eels. In Flanders, the IJzer estuary in Nieuwpoort, the ‘Sas Slijkens’ lock complex at the mouth of the Ghent-Ostend Canal (KGO), and the Zeebrugge outfall complex (mouth of the Afleidingskanaal van de Leie, AKL, and the Leopoldkanaal, LK) are crucial entry routes for glass eels. Previous research analysed glass eel migration and evaluated possible mitigation measures at sluice gates in the Ganzepoot (IJzer estuary), Sas Slijkens (KGO), and Zeebrugge outfall complex. Opening sluice gates ajar during the rising tide proved to be an effective and cost-efficient method to improve upstream migration, without the risk of salinisation of the polders due to seawater inflow. No alternative sluice management was applied at these sites in 2015. Nevertheless, increased conductivity values were measured, as reported in the internal report ‘Monitoring of salt intrusion in the Yser, Ghent-Ostend Canal, Leopold Canal and Leie Diversion Canal: Zero Measurement 2015’ by the Institute for Nature and Forest Research (INBO). These baseline measurements showed regularly elevated conductivity, especially near drainage structures and further upstream. The higher values were attributed to site-specific management or natural salinisation, especially during dry periods with low discharge. From 2016, alternative sluice management was applied. The results were reported in successive internal reports. In 2023, alternative sluicing management was continued from 1 March to 15 May. The application of alternative sluicing management varies greatly by watercourse. This is related to differences in target levels (m TAW), which affects the time window available for sluice management. In addition, some drainage structures, such as the Ganzepoot on the IJzer, are permanently manned, allowing management to take place outside office hours, unlike the AKL and LK.

Salt intrusion due to adapted sluice management seems to occur mainly in the Iron Basin, where peaks in conductivity strongly coincide with moments of adapted sluice management. This is largely explained by the intensive application of this measure in the Yser, resulting in the successful migration of an estimated 250,000 glass eels. In comparison, estimates for other watercourses show significantly lower numbers of migrating glass eels. In the Lys River Diversion Canal (AKL), sporadically applied sluice management has no discernible effect on conductivity in 2023. The number of glass eels that could migrate here is only 3% of the number swimming up the Yser. In the Ghent-Ostend Canal (KGO) and the Leopold Canal (LK), this percentage is 19% and 12% respectively. Here there is a more intensive application of adapted sluice management, which does lead to increased conductivity near the sluice gates. Unlike in the IJzer, however, these effects are limited to the immediate surroundings and no increases are observed deeper inland. In the Noordede, the modified sluice management had no significant impact on conductivity in 2023, despite a total duration about twice as long as in the Ghent-Ostend Canal and the Leopold Canal. This difference can possibly be attributed to the specific frequency and duration of the spui moments. In the Noordede, the spouts were opened for about half the total time period of the Yser, but the number of spill times was twice as high, with shorter spill times at a time. This strategy of shorter, more frequent and well-timed spawning moments seems to have advantages. Glass eels typically gather at barriers before they can migrate. Creating several shorter moments of sluice management facilitates the migration of glass eels and can reduce salt intrusion. This highlights the importance of a site-specific approach and a carefully tuned timing of sluice management to achieve both ecological and hydrological goals.

\eenglish
