\benglish

# English abstract {.unnumbered}

The European eel (*Anguilla anguilla L.*) has been facing a sharp population decline in Europe for decades and is now among the most endangered fish species on the continent. One of the main bottlenecks for the population is the limited upstream migration of glass eels. In Flanders, the Yser estuary in Nieuwpoort, the "Sas Slijkens" lock complex at the mouth of the Ghent-Ostend Canal (KGO), and the discharge complex in Zeebrugge (mouth of the Leie Diversion Canal, AKL, and the Leopold Canal, LK) form crucial entry routes for glass eels.

Previous research analysed glass eel migration and evaluated potential mitigating measures at sluice structures in the Ganzepoot (Yser estuary), Sas Slijkens (KGO), and the Zeebrugge discharge complex. Leaving sluice gates ajar during high tide proved to be an effective and cost-efficient method to improve upstream migration without the risk of salinisation of the polders due to seawater intrusion. In 2015, no adjusted tidal barrier management was applied at these locations. Nevertheless, increased conductivity values were measured, as reported in the internal report "Monitoring of salt intrusion in the Yser, the Ghent-Ostend Canal, the Leopold Canal and the Leie Diversion Canal: Baseline Measurement 2015" by the Research Institute for Nature and Forest (INBO). These baseline measurements regularly showed elevated conductivity, particularly near discharge structures and further upstream. The higher values were attributed to location-specific management or natural salinisation, especially during dry periods with low discharge.

Adjusted tidal barrier management has been applied since 2016, with results reported in subsequent internal reports. In 2025, the adjusted tidal barrier management was planned to run from March 1st to May 15th, but due to the dry spring, it was prematurely halted and not restarted at most sites. The application of adjusted tidal barrier management varies greatly per waterway. This is related to differences in target water levels (m TAW), which influences the available time window for sluice operation. Furthermore, some discharge structures, such as the Ganzepoot on the Yser, are permanently manned, allowing management to take place outside of office hours, unlike the AKL and LK.

The adjusted tidal barrier management played a varying, but crucial, role in glass eel migration along the Flemish coast between 2022 and 2024, resulting in a sharp increase in the number of migrating glass eels to a peak of 671,014 in 2024. The Yser experienced the most intensive deployment and the most pronounced salt intrusion, with conductivity peaks strongly correlating with the Adapted Sluice (AS) moments. However, this intensive approach supported the migration of a significant number of glass eels. In the Ghent-Ostend Canal (KGO) and the Leopold Canal (LK), the adjusted tidal barrier management did result in increased salinity near the sluice gates, but inland increases were largely absent in 2023 and 2024. The Leie Diversion Canal (AKL) saw the least intensive deployment, with no significant effect on inland conductivity, while in the Noordede, short but numerous AS events proved to be an effective method for limiting local salt intrusion. Generally, the salt lenses could be quickly and easily flushed out to sea during this period. However, the early cessation of management and the resulting estimated decline to 315,794 glass eels in 2025 was necessary because salt intrusion became critical early on due to the dry spring. This highlights the vulnerability of the management during drought periods and emphasises the importance of effective monitoring and swift action.

In addition to continuing the monitoring, it is advised to conduct a more detailed analysis that allows for the optimization of the moments, frequency, and duration of the adjusted tidal barrier management in function of both the control of salt intrusion and the promotion of upstream fish migration.

\eenglish
