\bfrench

# Résumé français {.unnumbered}

L'anguille européenne (Anguilla anguilla L.) est confrontée à un fort déclin de sa population en Europe depuis des décennies et fait désormais partie des espèces de poissons les plus menacées d'Europe. L'un des principaux goulets d'étranglement de la population est la migration limitée des civelles vers l'amont. En Flandre, l'estuaire de l'IJzer à Nieuwpoort, le complexe d'écluses « Sas Slijkens » à l'embouchure du canal Gand-Ostende (KGO) et le complexe d'émissaires de Zeebrugge (embouchure de l'Afleidingskanaal van de Leie, AKL, et du Leopoldkanaal, LK) sont des voies d'entrée cruciales pour les civelles. Des recherches antérieures ont analysé la migration des civelles et évalué les mesures d'atténuation possibles au niveau des vannes du Ganzepoot (estuaire de l'IJzer), de Sas Slijkens (KGO) et du complexe d'émissaires de Zeebrugge. L'ouverture des vannes à marée montante s'est avérée être une méthode efficace et rentable pour améliorer la migration vers l'amont, sans risque de salinisation des polders en raison de l'afflux d'eau de mer. Aucune gestion alternative des vannes n'a été appliquée sur ces sites en 2015. Néanmoins, des valeurs de conductivité accrues ont été mesurées, comme indiqué dans le rapport interne « Monitoring of salt intrusion in the Yser, Ghent-Ostend Canal, Leopold Canal and Leie Diversion Canal : Zero measurement 2015 » par l'Institut pour la recherche sur la nature et la forêt (INBO). Ces mesures de base ont révélé une conductivité régulièrement élevée, en particulier à proximité des structures de drainage et plus en amont. Les valeurs plus élevées ont été attribuées à une gestion spécifique du site ou à une salinisation naturelle, en particulier pendant les périodes sèches avec un faible débit. À partir de 2016, une gestion alternative des écluses a été appliquée. Les résultats ont été présentés dans des rapports internes successifs. En 2023, la gestion alternative des écluses a été poursuivie du 1er mars au 15 mai. L'application de la gestion alternative de l'éclusée varie considérablement d'un cours d'eau à l'autre. Ceci est lié aux différences dans les niveaux cibles (m TAW), qui affectent la fenêtre temporelle disponible pour la gestion de l'éclusée. En outre, certains ouvrages de drainage, tels que le Ganzepoot sur l'IJzer, sont occupés en permanence, ce qui permet d'effectuer la gestion en dehors des heures de bureau, contrairement à l'AKL et à la LK.

L'intrusion de sel due à une gestion adaptée des écluses semble se produire principalement dans le bassin ferrifère, où les pics de conductivité coïncident fortement avec les moments de gestion adaptée des écluses. Cela s'explique en grande partie par l'application intensive de cette mesure dans l'Yser, qui a permis la migration d'environ 250 000 civelles. En comparaison, les estimations pour d'autres cours d'eau montrent des nombres significativement plus faibles de civelles migrantes. Dans le canal de dérivation de la Lys (AKL), la gestion sporadique des écluses n'a pas d'effet perceptible sur la conductivité en 2023. Le nombre de civelles qui pourraient migrer ici ne représente que 3 % du nombre de civelles remontant l'Yser. Dans le canal Gand-Ostende (KGO) et le canal Léopold (LK), ce pourcentage est respectivement de 19% et 12%. Ici, la gestion adaptée des écluses est plus intensive, ce qui entraîne une augmentation de la conductivité à proximité des écluses. Contrairement à l'IJzer, ces effets sont toutefois limités aux environs immédiats et aucune augmentation n'est observée plus profondément dans les terres. Dans la Noordede, la gestion modifiée des écluses n'a pas eu d'impact significatif sur la conductivité en 2023, malgré une durée totale environ deux fois plus longue que dans le canal Gand-Ostende et le canal Léopold. Cette différence peut éventuellement être attribuée à la fréquence et à la durée spécifiques des moments de spui. Dans la Noordede, les becs ont été ouverts pendant environ la moitié de la durée totale de l'Yser, mais le nombre de périodes de déversement a été deux fois plus élevé, avec des périodes de déversement plus courtes à la fois. Cette stratégie de moments de frai plus courts, plus fréquents et bien programmés semble présenter des avantages. Les civelles se rassemblent généralement au niveau des barrières avant de pouvoir migrer. La création de plusieurs moments plus courts de gestion des écluses facilite la migration des civelles et peut réduire l'intrusion de sel. Cela souligne l'importance d'une approche spécifique au site et d'une gestion des écluses soigneusement synchronisée pour atteindre les objectifs écologiques et hydrologiques.

\efrench
