# Aanbevelingen voor beheer

Dit onderzoek richtte zich op de verdere optimalisatie van alternatief spuibeheer, dat in eerder onderzoek werd geïdentificeerd als een kostenefficiënte en effectieve maatregel om de stroomopwaartse glasaalmigratie te bevorderen, zonder significante instroom van zeewater.

Uit nulmetingen in 2015 (het referentiejaar waarin geen alternatief spuibeheer werd toegepast) bleek dat er regelmatig verhoogde geleidbaarheid werd gemeten op verschillende locaties, zowel nabij de uitwateringsconstructies als verder stroomopwaarts in de waterlopen en kanalen. Deze verhoogde waarden waren vaak toe te schrijven aan natuurlijke verzilting (vooral tijdens droge periodes met lage afvoer) of locatie-specifiek beheer (zie intern rapport INBO 2015).

Op basis van historische gegevens (INBO-rapporten: 2012–2022) en de metingen uitgevoerd vóór, tijdens (1 maart – 15 mei) en na de toepassing van alternatief spuibeheer in 2023, kan worden geconcludeerd dat dit aangepaste beheer met het oog op glasaalmigratie weinig risico’s inhoudt op significante stijgingen van de geleidbaarheid in de waterlopen.

Als aanvullende veiligheidsmaatregel werd met de waterbeheerder afgesproken om het alternatief spuibeheer in het AKL en LK onmiddellijk stop te zetten indien de vastgelegde limietwaarden worden overschreden. Het wordt aanbevolen om ook voor de IJzer en het KGO absolute limietwaarden te definiëren. Dit maakt een eventuele vroegtijdige stopzetting van het alternatief spuibeheer eenvoudiger en beter onderbouwd.
