# Aanbevelingen voor beheer {.unnumbered}

Dit onderzoek richtte zich op de verdere optimalisatie van het aangepast spuibeheer, dat in eerder onderzoek werd geïdentificeerd als een kostenefficiënte en effectieve maatregel om de stroomopwaartse glasaalmigratie te bevorderen, zonder significante instroom van zeewater. Uit nulmetingen in 2015 (het referentiejaar waarin geen alternatief spuibeheer werd toegepast) bleek dat er regelmatig verhoogde geleidbaarheid werd gemeten op verschillende locaties, zowel nabij de uitwateringsconstructies als verder stroomopwaarts in de waterlopen en kanalen. Deze verhoogde waarden waren vaak toe te schrijven aan natuurlijke verzilting (vooral tijdens droge periodes met lage afvoer) of locatie-specifiek beheer (zie intern rapport INBO 2015). Op basis van historische gegevens (INBO-rapporten: 2012–2024) en de metingen uitgevoerd vóór, tijdens (1 maart – 15 mei) en na de toepassing van alternatief spuibeheer in 2025, kan worden geconcludeerd dat dit aangepaste beheer met het oog op glasaalmigratie weinig risico’s inhoudt op significante stijgingen van de geleidbaarheid in de waterlopen onder normale omgevingsomstandigheden. In het geval van uitzonderlijke droogte in het voorjaar, zoals het geval in 2025, is goede monitoring en tijdig ingrijpen wel belangrijk om zoutintrusie tegen te gaan. De aanvullende veiligheidsmaatregel om het aangepast spuibeheer in het AKL, LK, de Ijzer en het KGO onmiddellijk stop te zetten indien de vastgelegde limietwaarden worden overschreden werd in 2025 met succes uitgevoerd in de Ijzer, het Leopoldskanaal en het Afleidingskanaal van de Leie.

Droge periodes zullen in de toekomst wellicht frequenter voorkomen en de uitdagingen waar migrerende vissen voor staan zullen niet minder worden. Een verderzetting van het aangepast spuibeheer blijft daarom heel belangrijk. Onderzoek naar het beste moment, de duur en de frequentie van het openen van de spuischuiven kan een belangrijke reductie in zoutintrusie betekenen zonder in te boeten op de voordelen voor migrerende vissen.
