# Bespreking

Zoutintrusie als gevolg van aangepast spuibeheer lijkt zich voornamelijk voor te doen in het Ijzerbekken waar de pieken in geleidbaarheid sterk overeenkomen met de momenten van aangepast spuibeheer. Belangrijk om hierbij te noteren is echter wel dat ter hoogte van de Ijzer het meest intensieve aangepast spuibeheer wordt uitgevoerd en dat daardoor ook ruw geschat 250.000 glasalen kunnen opzwemmen [@vandamme2024]. Inschattingen suggereren dat voor de andere kanalen een aanzienlijk lager aantal kan opzwemmen. In het Afleidingskanaal van de Leie bijvoorbeeld is er geen waarneembaar effect van het sporadische aangepast spuibeheer maar het ingeschat aantal glasalen dat binnentrekt in 2023 is slechts 3% van wat er de Ijzer op trekt. In het Kanaal Gent-Oostende en het Leopoldkanaal spreken we over percentages van 19 en 12% respectievelijk van wat de Ijzer opzwemt en deze meer intensieve vorm van aangepast spuibeheer lijkt te resulteren in een verhoogde geleidbaarheid ter hoogte van de spuischuiven. In tegenstelling tot de Ijzer, blijven meer inlandse verhogingen van de geleidbaarheid uit. In de Noordede werd er geen aanzienlijk effect waargenomen van aangepast spuibeheer op de geleidbaarheid ondanks het feit dat de totale duur in 2023 ongeveer twee keer zo lang was als voor het Kanaal Gent-Oostende en het Leopoldkanaal. Dit is mogelijks het gevolg van de frequentie van en de duur van de aangepast-spuibeheer-momenten. In de Noordede werd aangepast spuibeheer toegepast voor ongeveer de helft van de duur aan de Ijzer, maar het aantal momenten dat aangepast spuibeheer werd toegepast lag wel ongeveer tweemaal zo hoog. De duur van een enkel moment was dus veel korter. Gegeven dat glasalen zich ophopen voor barrières alvorens te kunnen passeren kunnen meerdere, kortere en goed getimede momenten zowel de glasaalintrek bevorderen en de zoutintrusie beperken. Deze studie suggereert dat de intensiteit van het aangepast spuibeheer deels bepalend is voor de mate van zoutintrusie, maar ook dat verschillende aspecten van het beheer, zoals frequentie en duur, een belangrijk effect kunnen hebben.

## Vergelijking VMM-logger en INBO-loggers conductiviteit

Wanneer we voor de Ijzer de INBO-data en de VMM-data vergelijken, wordt duidelijk hoe belangrijk de diepte van de metingen is (Fig. \@ref(fig:plotcondijzer)). Op de bodem van het spaarbekken komen de drie uitgesproken pieken (die wellicht het gevolg zijn van het aangepast spuibeheer) die ook in de INBO-metingen te zien zijn, terug, maar aan de oppervlakte van het spaarbekken is hier niets van te merken. De INBO-loggers worden telkens zo diep mogelijk geplaatst terwijl voor de VMM-loggers de diepte verschilt (maar dit verschil is wel veelal aangegeven). Het is dus cruciaal om loggers voldoende diep te plaatsen (i.e. ongeveer 10 cm van de bodem) en bij voorkeur ook een indicatie te geven van de diepte tov een vast referentieniveau (bijvoorbeeld mTAW). In 2023 was het aantal beschikbare VMM-loggers beperkt tot negen voor de Ijzer, één voor het Kanaal Gent-Oostende en één voor de Noordede. Het vervangen van de INBO-loggers door VMM-loggers wordt aangeraden omwille van de winst aan tijdsefficiëntie door het verwijderen van redundante loggers en omwille van de mogelijkheid van de VMM-loggers om live metingen op te volgen. Daarenboven biedt dit de mogelijkheid om veel sneller in te grijpen in het aangepast spuibeheer wanneer limietwaarden worden overschreden.
