# Bespreking

Zoutintrusie als gevolg van aangepast spuibeheer lijkt zich voornamelijk voor te doen in het Ijzerbekken waar de pieken in geleidbaarheid sterk overeenkomen met de momenten van aangepast spuibeheer. Belangrijk om hierbij te noteren is echter wel dat ter hoogte van de Ijzer het meest intensieve aangepast spuibeheer wordt uitgevoerd en dat daardoor ook ruw geschat 250.000 glasalen kunnen opzwemmen. Inschattingen suggereren dat voor de andere kanalen een aanzienlijk lager aantal kan opzwemmen. In het Afleidingskanaal van de Leie bijvoorbeeld is er geen waarneembaar effect van het sporadische aangepast spuibeheer maar het ingeschat aantal glasalen dat binnentrekt in 2023 is slechts 3% van wat er de Ijzer op trekt. In het Kanaal Gent-Oostende en het Leopoldskanaal spreken we over percentages van 19 en 12% respectievelijk van wat de Ijzer opzwemt en deze meer intensieve vorm van aangepast spuibeheer lijkt te resulteren in een verhoogde geleidbaarheid ter hoogte van de spuischuiven. In tegenstelling tot de Ijzer, blijven meer inlandse verhogingen van de geleidbaarheid uit. In de Noordede werd er geen aanzienlijk effect waargenomen van aangepast spuibeheer op de geleidbaarheid ondanks het feit dat de totale duur in 2023 ongeveer twee keer zo lang was als voor het Kanaal Gent-Oostende en het Leopoldskanaal. Dit is mogelijks het gevolg van de frequentie van en de duur van de aangepast-spuibeheer-momenten. In de Noordede werd aangepast spuibeheer toegepast voor ongeveer de helft van de duur aan de Ijzer, maar het aantal momenten dat aangepast spuibeheer werd toegepast lag wel ongeveer tweemaal zo hoog. De duur van een enkel moment was dus veel korter. Gegeven dat glasalen zich ophopen voor barrières alvorens te kunnen passeren kunnen meerdere, kortere en goed getimede momenten zowel de glasaalintrek bevorderen en de zoutintrusie beperken. Deze studie suggereert dat de intensiteit van het aangepast spuibeheer deels bepalend is voor de mate van zoutintrusie, maar ook dat verschillende aspecten van het beheer, zoals frequentie en duur, een belangrijk effect kunnen hebben.
