# Conclusie

Het aangepast spuibeheer (AS) ondersteunde de glasaalmigratie effectief in **2023 en 2024**, met een piek van **671.014** glasalen in het laatste jaar. De resultaten van **2025** tonen echter de kwetsbaarheid van dit beheer aan, met een daling tot slechts **315.794** glasalen als gevolg van de vroegtijdige stopzetting veroorzaakt door droogte.

## Vroegtijdige Stopzetting door Zoutintrusie

De daling in 2025 was een direct gevolg van het **sterk gereduceerd en vroegtijdig stopgezet AS** in alle waterlopen vanwege **zoutintrusie** door **lage bovenafvoer**.

-   De **Ijzer** had de **laagste AS-duur** (**217 uren**) in de periode, maar de geleidbaarheid lag **aanzienlijk hoger** door het watertekort, wat leidde tot stopzetting op **21 maart 2025**.

-   In het **Afleidingskanaal van de Leie (AKL)** en het **Leopoldkanaal (LK)** leidde de lage bovenafvoer ertoe dat het AS, ondanks beperkte duur, nu wél kritische **zoutverhoging in Ramskapelle** veroorzaakte, wat in **2023 en 2024** niet het geval was. Beide complexen werden stopgezet op **28 maart 2025**.

<!-- -->

-   In het **Kanaal Gent-Oostende (KGO)** leek het AS in 2024 en 2025 wel lokaal de geleidbaarheid te beïnvloeden, maar **effecten bleven landinwaarts uit**. Daarom werd het AS hier niet stopgezet.

Kortom, de resultaten van 2025 benadrukken dat de ondersteuning van de glasaalmigratie door AS in toenemende mate wordt belemmerd door de verzilting van het watersysteem tijdens droge periodes en dat goede opvolging cruciaal blijft.
