\bdutch

# Nederlandstalige samenvatting {.unnumbered}

De Europese palingpopulatie (*Anguilla anguill*a L.) is de afgelopen decennia sterk afgenomen en wordt nu beschouwd als een van de meest bedreigde vissoorten in Europa. Een belangrijke factor die bijdraagt aan deze achteruitgang is de beperking van de stroomopwaartse migratie van glasaal. In Vlaanderen vormen de IJzermonding in Nieuwpoort, het sluizencomplex "Sas Slijkens" aan de monding van het Kanaal Gent-Oostende en het uitwateringscomplex in Zeebrugge bij de monding van het Afleidingskanaal van de Leie (AKL) en het Leopoldkanaal (LK) cruciale intrekroutes voor glasaal.

Eerder onderzoek heeft zich gericht op de migratie van glasaal en mogelijke mitigerende maatregelen bij de spuiconstructies van de Ganzepoot (IJzermonding), het Sas Slijkens (KGO) en het uitwateringscomplex van Zeebrugge. Hieruit bleek dat het op een kier zetten van de sluisdeur tijdens het opkomend tij een effectieve en kostenefficiënte maatregel is om de stroomopwaartse migratie van glasaal te bevorderen, zonder dat dit leidt tot verzilting van de polders door instroom van zeewater.

In 2015 werd op geen enkele van deze cruciale locaties aangepast spuibeheer toegepast. Toch werden verhoogde waarden van elektrische geleidbaarheid gemeten, zoals gerapporteerd in het Intern Rapport van het Instituut voor Natuur- en Bosonderzoek over de nulmeting van dat jaar. De metingen lieten zien dat de geleidbaarheid op verschillende locaties regelmatig verhoogd was, vooral nabij de uitwateringsconstructies en verder stroomopwaarts. Mogelijke oorzaken waren locatie-specifiek beheer of natuurlijke verzilting, met name tijdens drogere periodes met verminderde afvoer.

Tussen 2016 en 2021 werd aangepast spuibeheer ingevoerd en geëvalueerd. In 2022 vond dit beheer plaats tussen 1 maart en 15 mei. De toepassing ervan verschilde per waterloop, onder andere door verschillen in streefpeilen en tijdsvensters voor spuibeheer. Daarnaast speelt personeelsbezetting een rol: bij de IJzer (Ganzepoot) is er permanente bemanning door binnenvaartbegeleiders, waardoor aangepast spuibeheer ook buiten kantooruren, inclusief ’s nachts, kan worden uitgevoerd. Dit in tegenstelling tot de uitwateringsconstructies bij het AKL en het LK, waar deze mogelijkheid ontbreekt.

Eerdere studies toonden aan dat de kansen om de palingdensiteit in het LK te verhogen onderbenut bleven [@Steendam2019], doordat het aangepaste spuibeheer in Zeebrugge (LK en AKL) beperkter werd toegepast dan bij andere waterlopen zoals het Kanaal Gent-Oostende en de IJzer. Om dit te verbeteren, werd in 2021 geprobeerd om het aangepast spuibeheer in het LK te intensiveren door de schuiven ook met afgaand tij open te houden, waardoor er twee keer per etmaal gespuid kon worden. Op 3 maart 2021 werd voor het eerst glasaal binnengelaten in het LK, en de schuiven bleven continu open tot 9 maart. Dit leidde echter tot hoge zoutwaarden, waardoor het aangepast spuibeheer tijdelijk werd stopgezet van 10 tot 18 maart. Vanaf 19 maart werd het spuibeheer hervat, maar enkel overdag, zoals in voorgaande jaren. In 2022 werd opnieuw het oorspronkelijke beheer toegepast, waarbij de schuiven uitsluitend overdag openstonden.

Het aangepast spuibeheer in de IJzer is relatief intensief in vergelijking met andere systemen waar aangepast spuibeheer wordt toegepast. In de IJzer is er dan ook een duidelijke relatie tussen periodes van aangepast spuibeheer en een verhoogde conductiviteit. Dit jaar bleef de conductiviteit echter ook na de periode van aangepast beheer bijzonder hoog, waarschijnlijk als gevolg van de droge zomer. In tegenstelling tot 2021 was de zomer van 2022 namelijk uitzonderlijk droog.

\edutch
