# Aanbevelingen voor beheer {.unnumbered}

Dit onderzoek had als doel de verdere optimalisatie van het alternatief spuibeheer, dat in eerder onderzoek werd geïdentificeerd als een kostenefficiënte en effectieve maatregel om de stroomopwaartse migratie van glasaal te bevorderen zonder significante instroom van zeewater.

Nulmetingen in 2015 (het jaar voorafgaand aan de implementatie van alternatief spuibeheer) toonden aan dat verhoogde geleidbaarheidswaarden regelmatig werden gemeten op verschillende locaties, zowel nabij de uitwateringsconstructies als verder stroomopwaarts in diverse waterlopen en kanalen. Deze hogere waarden werden vaak toegeschreven aan natuurlijke verzilting (met name in drogere periodes met verminderde afvoer) of locatie-specifiek beheer (zie INBO intern rapport, 2015).

Op basis van historische metingen (INBO interne rapporten: 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020 en 2021) en de metingen die werden uitgevoerd vóór, tijdens (tussen 28 februari en 15 mei) en na de toepassing van alternatief spuibeheer in 2022, kan worden geconcludeerd dat deze aangepaste beheersmaatregel ter ondersteuning van glasaalmigratie slechts een minimaal risico op significante stijgingen in geleidbaarheid in de verschillende waterlopen met zich meebrengt.

Daarnaast werd als preventieve veiligheidsmaatregel met de waterbeheerder overeengekomen dat alternatief spuibeheer in onmiddellijk wordt stopgezet indien vastgelegde limietwaarden worden overschreden.
