# Bespreking

In 2022 werd er alternatief spuibeheer toegepast op enkele van de belangrijke intrekroutes voor glasaal in Vlaanderen, namelijk in de IJzermonding in Nieuwpoort, in het complex “Sas Slijkens” aan de monding van het Kanaal Gent-Oostende en in het uitwateringscomplex in de haven van Zeebrugge aan de monding van het Afleidingskanaal van de Leie (AKL) en van het Leopoldkanaal (LK) (Figuur 23). Alternatief spuibeheer is één van de maatregelen die waterbeheerders kunnen nemen om stroomopwaartse migratie van glasaal ter hoogte van deze locaties opnieuw mogelijk te maken. Net zoals de voorbijgaande jaren, was de spuiduur het grootst aan de IJzermonding in de Ganzepoot (276:43 uren in totaal). Maar dit is wel bijna een halvering ten opzichte van 2021 (489 uren). Op KGO is er dit jaar (245:46 uur in totaal) beduidend meer gespuid dan de voorbije jaren. In vergelijking met vorige jaren is er door werkzaamheden aan de spuikoker op het AKL een pak minder gespuid (18:50 uur in totaal). Op het LK  zijn er ongeveer evenveel dagen gespuid als vorig jaar, maar is het aantal uren gehalveerd ten opzichte van vorig jaar. Dit kwam doordat er terug naar het oude systeem gegaan is waarbij de schoten enkel overdag open stonden. 

Het alternatieve spuibeheer in de Ijzer is relatief intensief in vergelijking met de andere systemen waar aangepast spuibeheer wordt uitgevoerd. In de Ijzer zien we dan ook een link tussen periodes van aangepast spuibeheer en een verhoogde hoge conductiviteit in de Ijzer. Dit jaar bleef de conductiviteit echter na de periode van het aangepast beheer ook bijzonder hoog wat wellicht het gevolg is van de droge zomer. In tegenstelling tot 2021, was de zomer van 2022 immers bijzonder droog. Ondanks er geen sluitende bewijzen zijn voor een effect van het alternatief spuibeheer in de andere kanalen, lijkt het erop dat droge periodes een versterkend effect hebben op het aangepast spuibeheer in deze systemen. 