\benglish

# English abstract {.unnumbered}

The European eel (*Anguilla anguilla L.*) has been facing a sharp decline in population in Europe for decades and is now one of the most endangered fish species in Europe. One of the main bottlenecks for the population is the limited upstream migration of glass eels. In Flanders, the IJzer estuary in Nieuwpoort, the Sas Slijkens lock complex at the mouth of the Ghent-Ostend Canal (KGO), and the drainage complex in Zeebrugge (mouth of the Leie Diversion Canal, AKL, and the Leopold Canal, LK) are crucial migration routes for glass eels.

Previous research analysed glass eel migration and evaluated possible mitigation measures at sluice structures in the Ganzepoot (Ijzermonding), Sas Slijkens (KGO), and the Zeebrugge drainage complex. Leaving sluice gates ajar during the rising tide proved to be an effective and cost-efficient method of improving upstream migration without the risk of salinisation of the polders due to seawater inflow.

In 2015, no adjusted tidal barrier management was applied at these locations. Nevertheless, increased conductivity values were measured, as reported in the internal report “Monitoring of salt intrusion in the IJzer, the Ghent-Ostend Canal, the Leopold Canal and the Leie Diversion Canal: Baseline measurement 2015” by the Research Institute for Nature and Forestry (INBO). These baseline measurements showed regularly elevated conductivity, especially near drainage structures and further upstream. The higher values were attributed to location-specific management or natural salinisation, particularly during dry periods with low discharge.

From 2016 onwards, adjusted tidal barrier management was applied. The results of this were reported in successive internal reports. In 2023, adjusted tidal barrier management was continued from 1 March to 15 May. The application of adjusted tidal barrier management varies greatly per watercourse. This is related to differences in target levels (m TAW), which influences the available time window for adjusted tidal barrier management. In addition, some drainage structures, such as the Ganzepoot on the Ijzer, are permanently manned, which means that management can also take place outside office hours, in contrast to the AKL and LK.

Salt intrusion as a result of adjusted tidal barrier management seems to occur mainly in the Yser basin, where peaks in conductivity usually coincide with moments of adjusted tidal barrier management. This can largely be explained by the intensive application of this measure in the Yser, which results in the successful migration of an estimated 250,000 glass eels.

By comparison, estimates for other watercourses show significantly lower numbers of migrating glass eels. In the Leie Diversion Canal (AKL), the sporadic application of adjusted tidal barrier management in 2023 has no observable effect on conductivity. The estimated number of glass eels that were able to migrate here amounts to only 3% of the number that swim up the Yser.

In the Ghent-Ostend Canal (KGO) and the Leopold Canal (LK), this percentage is 19% and 12% respectively. For the KGO and LK, there is a more intensive application of adjusted tidal barrier management than in the AKL, which does lead to increased conductivity near the sluice gates of the KGO and LK at times of adjusted tidal barrier management. Unlike the Ijzer, however, these effects are limited to the immediate vicinity and no increases are observed further inland.

In the Noordede,adjusted tidal barrier management in 2023 had no significant impact on conductivity, despite a total duration that was approximately twice as long as in the Ghent-Ostend Canal and the Leopold Canal. This difference can possibly be attributed to the specific frequency and duration of the sluice openings. In the Noordede, the sluices were opened for approximately half the total duration of the IJzer, but the number of sluicing moments was twice as high, with shorter sluicing moments per instance. This strategy of shorter, more frequent and well-timed sluicing moments appears to offer advantages.

Glass eels typically gather at barriers before they can migrate. Creating multiple shorter moments of adjusted tidal barrier management facilitates the migration of glass eels and can limit salt intrusion. This emphasises the importance of a location-specific approach and carefully coordinated timing of adjusted tidal barrier management to achieve both ecological and hydrological goals.

\eenglish
